//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojChecador.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class ChecadorEntities : DbContext
    {
        public ChecadorEntities()
            : base("name=ChecadorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GRUPO> GRUPO { get; set; }
        public DbSet<HORA_CLASE> HORA_CLASE { get; set; }
        public DbSet<HORARIO> HORARIO { get; set; }
        public DbSet<MATERIA> MATERIA { get; set; }
        public DbSet<PROFESOR> PROFESOR { get; set; }
        public DbSet<REGISTRO_ASISTENCIA> REGISTRO_ASISTENCIA { get; set; }
        public DbSet<RETARDO> RETARDO { get; set; }
    
        public virtual int CALCULOINSERCIONRETARDO(Nullable<decimal> p_IDHORARIO, Nullable<decimal> p_IDREGISTROASISTENCIA, Nullable<System.DateTime> p_HORA)
        {
            var p_IDHORARIOParameter = p_IDHORARIO.HasValue ?
                new ObjectParameter("P_IDHORARIO", p_IDHORARIO) :
                new ObjectParameter("P_IDHORARIO", typeof(decimal));
    
            var p_IDREGISTROASISTENCIAParameter = p_IDREGISTROASISTENCIA.HasValue ?
                new ObjectParameter("P_IDREGISTROASISTENCIA", p_IDREGISTROASISTENCIA) :
                new ObjectParameter("P_IDREGISTROASISTENCIA", typeof(decimal));
    
            var p_HORAParameter = p_HORA.HasValue ?
                new ObjectParameter("P_HORA", p_HORA) :
                new ObjectParameter("P_HORA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CALCULOINSERCIONRETARDO", p_IDHORARIOParameter, p_IDREGISTROASISTENCIAParameter, p_HORAParameter);
        }
    
        public virtual int CALCULOPAGO(Nullable<decimal> p_IDPROFESOR, Nullable<decimal> p_IDPAGO, Nullable<System.DateTime> p_FECHAINICIO, Nullable<System.DateTime> p_FECHAFIN)
        {
            var p_IDPROFESORParameter = p_IDPROFESOR.HasValue ?
                new ObjectParameter("P_IDPROFESOR", p_IDPROFESOR) :
                new ObjectParameter("P_IDPROFESOR", typeof(decimal));
    
            var p_IDPAGOParameter = p_IDPAGO.HasValue ?
                new ObjectParameter("P_IDPAGO", p_IDPAGO) :
                new ObjectParameter("P_IDPAGO", typeof(decimal));
    
            var p_FECHAINICIOParameter = p_FECHAINICIO.HasValue ?
                new ObjectParameter("P_FECHAINICIO", p_FECHAINICIO) :
                new ObjectParameter("P_FECHAINICIO", typeof(System.DateTime));
    
            var p_FECHAFINParameter = p_FECHAFIN.HasValue ?
                new ObjectParameter("P_FECHAFIN", p_FECHAFIN) :
                new ObjectParameter("P_FECHAFIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CALCULOPAGO", p_IDPROFESORParameter, p_IDPAGOParameter, p_FECHAINICIOParameter, p_FECHAFINParameter);
        }
    
        public virtual int DECHORASPROFESOR(Nullable<decimal> p_IDPROFESOR, string p_DIASSEMANA)
        {
            var p_IDPROFESORParameter = p_IDPROFESOR.HasValue ?
                new ObjectParameter("P_IDPROFESOR", p_IDPROFESOR) :
                new ObjectParameter("P_IDPROFESOR", typeof(decimal));
    
            var p_DIASSEMANAParameter = p_DIASSEMANA != null ?
                new ObjectParameter("P_DIASSEMANA", p_DIASSEMANA) :
                new ObjectParameter("P_DIASSEMANA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DECHORASPROFESOR", p_IDPROFESORParameter, p_DIASSEMANAParameter);
        }
    
        public virtual int INCDECHORASPROFESOR(Nullable<decimal> p_IDPROFESOR, string p_DSEMANANEW, string p_DSEMANAANT)
        {
            var p_IDPROFESORParameter = p_IDPROFESOR.HasValue ?
                new ObjectParameter("P_IDPROFESOR", p_IDPROFESOR) :
                new ObjectParameter("P_IDPROFESOR", typeof(decimal));
    
            var p_DSEMANANEWParameter = p_DSEMANANEW != null ?
                new ObjectParameter("P_DSEMANANEW", p_DSEMANANEW) :
                new ObjectParameter("P_DSEMANANEW", typeof(string));
    
            var p_DSEMANAANTParameter = p_DSEMANAANT != null ?
                new ObjectParameter("P_DSEMANAANT", p_DSEMANAANT) :
                new ObjectParameter("P_DSEMANAANT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INCDECHORASPROFESOR", p_IDPROFESORParameter, p_DSEMANANEWParameter, p_DSEMANAANTParameter);
        }
    
        public virtual int INCREMENTOHORASPROFESOR(Nullable<decimal> p_IDPROFESOR, string p_DIASSEMANA)
        {
            var p_IDPROFESORParameter = p_IDPROFESOR.HasValue ?
                new ObjectParameter("P_IDPROFESOR", p_IDPROFESOR) :
                new ObjectParameter("P_IDPROFESOR", typeof(decimal));
    
            var p_DIASSEMANAParameter = p_DIASSEMANA != null ?
                new ObjectParameter("P_DIASSEMANA", p_DIASSEMANA) :
                new ObjectParameter("P_DIASSEMANA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INCREMENTOHORASPROFESOR", p_IDPROFESORParameter, p_DIASSEMANAParameter);
        }
    }
}
