//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojChecador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO
    {
        public GRUPO()
        {
            this.HORARIO = new HashSet<HORARIO>();
        }
    
        public long ID_GRUPO { get; set; }
        public string CICLO_ESCOLAR { get; set; }
        public int SEMESTRE { get; set; }
        public string GRUPO1 { get; set; }
    
        public virtual ICollection<HORARIO> HORARIO { get; set; }
    }
}
