//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojChecador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public HORARIO()
        {
            this.REGISTRO_ASISTENCIA = new HashSet<REGISTRO_ASISTENCIA>();
        }
    
        public long ID_HORARIO { get; set; }
        public long ID_HORA_CLASE { get; set; }
        public long ID_GRUPO { get; set; }
        public long ID_MATERIA { get; set; }
        public long ID_PROFESOR { get; set; }
        public string DIA_SEMANA { get; set; }
    
        public virtual GRUPO GRUPO { get; set; }
        public virtual HORA_CLASE HORA_CLASE { get; set; }
        public virtual MATERIA MATERIA { get; set; }
        public virtual PROFESOR PROFESOR { get; set; }
        public virtual ICollection<REGISTRO_ASISTENCIA> REGISTRO_ASISTENCIA { get; set; }
    }
}
