//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojChecador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESOR
    {
        public PROFESOR()
        {
            this.HORARIO = new HashSet<HORARIO>();
        }
    
        public long ID_PROFESOR { get; set; }
        public string NOMBRE1 { get; set; }
        public string NOMBRE2 { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public string CALLE { get; set; }
        public string NO_EXTERIOR { get; set; }
        public string NO_INTERIOR { get; set; }
        public int LADA { get; set; }
        public long TELEFONO { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string RFC { get; set; }
        public Nullable<int> HORAS_SEMANALES { get; set; }
        public string FIRMA { get; set; }
    
        public virtual ICollection<HORARIO> HORARIO { get; set; }
    }
}
