//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelojChecador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRO_ASISTENCIA
    {
        public REGISTRO_ASISTENCIA()
        {
            this.RETARDO = new HashSet<RETARDO>();
        }
    
        public long ID_REGISTRO_ASISTENCIA { get; set; }
        public long ID_HORARIO { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime HORA { get; set; }
    
        public virtual HORARIO HORARIO { get; set; }
        public virtual ICollection<RETARDO> RETARDO { get; set; }
    }
}
